### PR TITLE
Parse text

### LINKED ISSUE #58: Extend setCharacters with multistyles update
Related conversation:
https://figmaplugins.slack.com/archives/CHPTY6TFD/p1592231931354600

Proposed solution by @steffanwilliams:
https://gist.github.com/steffanwilliams/4d4be23780eb10dcd238200cf297b1b5

### PR DESCRIPTION
**Pull request by Andreslav**
Helpers for working with text styles.

– parseTextStyle
– splitTextStyleIntoLines
– joinTextLinesStyles
– createTextNodeFromTextStyle

изображение

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Andreslav Does it possible to extend `setCharacters` helper with this functionality?

**Comment by Andreslav** [comment]
> 
> 
> @Andreslav Does it possible to extend `setCharacters` helper with this functionality?

This assistant is more focused on working with styles, rather than changing text.
But 'set Characters' can use its functionality to save styles when changing text.

**Comment by Andreslav** [comment]
Added 
– changeCharactersTextStyle.
– changeTextStyle.

**Comment by Andreslav** [comment]
@alexandrtovmach Hello :)

**Review by alexandrtovmach — APPROVED** [review]
@Andreslav sorry, no time now. If you think it's okay, feel free to merge without review (added my approval for that)

**Pull request merged**
