### PR TITLE
Use Babel for build, and babel-lodash-plugin

### PR DESCRIPTION
**Pull request by LukeFinch**
lodash can bloat the size of a package if imported incorrectly. 

From my own testing my code.js went from 10kb to 1mb when importing a helper function.

babel-lodash-plugin will change the module imports to be lightweight and will treeshake any lodash functions. 

This only effects the output of the build, and won't change any of the development process when writing helpers

### CODE REVIEW

**Comment by LukeFinch** [comment]
Related issue: https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/issues/71

**Review by alexandrtovmach — APPROVED** [review]
Looks as reasonable solution! Thanks :+1:

**Comment by alexandrtovmach** [comment]
P.S. Sorry for delay

**Comment by LukeFinch** [comment]
> Looks as reasonable solution! Thanks 👍
> P.S. Sorry for delay

No worries! Hopefully that all works. :)

**Pull request merged**
