### PR TITLE
feat: Added node type checking helpers

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Comment by Andreslav** [comment]
I propose to rename the proposed methods according to the sample: `is*Node` -> `is*`.
For example, `isPageNode `-> `isPage`.

`isInstanceNode` do not touch. The option you offer does not allow you to check whether the node belongs to an instance.

What do you think about this method? I often need to check for multiple types at once
```
function isLikeType(node, types) {
  return types.find((e) => node.type == e) == node.type
} 
isLikeType(node, ["TEXT", "FRAME"])
```

**Comment by Andreslav** [comment]
@alexandrtovmach, what do you think?

**Comment by alexandrtovmach** [comment]
@Andreslav Thanks for a ping

I'm not agreed that `isPage` will be better than `isPageNode`. Second one give developer more context what happens inside function.
Yeah, about `isInstanceNode` I shouldn't remove them, and instead just rename to `isPartOfInstance`

About proposed `isLikeType`, again another name (please don't hate me 🙃) I think `isOneOfNodeType` or `isOneOfType`

Will update this PR soon

**Comment by alexandrtovmach** [comment]
@Andreslav I thought about that and here is my decisions:
1. If we declare arguments in that way `(node: BaseNode)` then we can't pass anything, like `undefined`, `null`, `{...some object... }`, and this looks strict and cool, but.... it require additional steps for developer before use. For example:
```
export const isInstanceNode = (node: BaseNode): node is InstanceNode => { ... }

isInstanceNode(myNode); // will not work, because myNode is not type of BaseNode

if (isBaseNode(myNode)) {
  isInstanceNode(myNode); // will work because we checked type before
}
```
2. About describing is `isOneOfNodeType` it's actually debatable, but for me personally it's not given a value if I know that myNode can be any of figma nodes type:
```
if (isOneOfNodeType(myNode, ["TEXT", "PAGE"])) {
  // myNode is going to be any of figma node types
}
```

I tried to find a way to make dynamic generic, to made types based on provided `typeList`, but no luck. Ideally it should be like:
```
if (isOneOfNodeType(myNode, ["TEXT", "PAGE"])) {
  // myNode is going to be PageNode or TextNode only
}
```

**Comment by Andreslav** [comment]
@alexandrtovmach however, this will also protect us from possible mistakes. Moreover, passing undefined at the moment will result in an error.

I suppose if I want to determine the type of node, I am sure that it is a node. And I will not try to check for a non-existent node type. Otherwise, it is pointless. Agree?

**Comment by Andreslav** [comment]
About `NodeType` poorly understood. `NodeType` is already defined in the figma.d.ts.

**Comment by alexandrtovmach** [comment]
Okay, agree with you

**Comment by Andreslav** [comment]
> 2. About describing is isOneOfNodeType it's actually debatable, but for me personally it's not given a value if I know that myNode can be any of figma nodes type.

Here is where you correctly noticed. Now I understand what you mean, thank you!

**Comment by Andreslav** [comment]
Thank you! @alexandrtovmach

**Pull request merged**
