### PR TITLE
feat: Replaced definitions with npm module

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Comment by Andreslav** [comment]
@alexandrtovmach  I have ts started swearing...



It seems figma.d.ts is not defined.

**Comment by alexandrtovmach** [comment]
@Andreslav it's problem related to VSCode, and solved in #23 
check tsconfig:
https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/blob/feat/get-text-css/tsconfig.json

**Comment by alexandrtovmach** [comment]
`"moduleResolution": "node"` - should help

**Comment by alexandrtovmach** [comment]
my fault that I didn't merge it separately from my changes

**Pull request merged**
