### PR TITLE
Patch/abs pos

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Comment by Andreslav** [comment]
Does the result differ from the values in `absoluteTransform`?

**Comment by alexandrtovmach** [comment]
@Andreslav Wow, never seen this property, seems like you right, but `relativeTransform`  it's what I'm looking for

**Comment by alexandrtovmach** [comment]
Sorry, seems like I've confused, that's not the same

**Comment by alexandrtovmach** [comment]
difference
image

**Comment by alexandrtovmach** [comment]
@Andreslav

**Comment by Andreslav** [comment]
@alexandrtovmach, hello!
Wow! Now I understand that the helper allows you to get a position relative to a specific parent frame.

The collector swears, and the function throws an exception 😑, helps `from './isTypeNode'`: https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/pull/32/files#diff-d061f4a86db8ff74d420b59c797b7d71R1

**Comment by alexandrtovmach** [comment]
@Andreslav how to reproduce issue from screenshot?

**Comment by Andreslav** [comment]
@alexandrtovmach  I test in my plugin, connect like this:
` import getRealtivePosition from '../../figma-plugin-helpers/src/helpers/getRealtivePosition';`

Connection in this way -
`import { getRealtivePosition } from '../../figma-plugin-helpers/src/index';`
- causes the same problems. 

Could the problem be my incorrectly configured webpack?

**Comment by alexandrtovmach** [comment]
@Andreslav of course it's a not right way for local package testing =)

To do this you need to actually install package with `npm/yarn` to your plugin:
```sh
npm i ../figma-plugin-helpers
# or
yarn add file:../figma-plugin-helpers
```

**Pull request merged**
